Questão 1-a) A matriz A2 = A · A, se refere ao fato de que a matriz ao quadrado, é ela vezes ela mesma. Ou seja A2 é a matriz resultante de A · A.

In [31]:
#Questão 1-B)
import numpy as np

matriz_a = np.array([
    [0, 1, 1, 1, 1],
    [1, 0, 1, 1, 0],
    [0, 1, 0, 1, 0],
    [0, 0, 1, 0, 1],
    [0, 0, 0, 1, 0]
])
matriz_a_2 = np.dot(matriz_a, matriz_a)
print(matriz_a_2)


[[1 1 2 3 1]
 [0 2 2 2 2]
 [1 0 2 1 1]
 [0 1 0 2 0]
 [0 0 1 0 1]]


Questão 1-c) C13 = 2 significa que existem exatos dois caminhos de comprimento 2, que podem sair da estação 1 e ir para a estação 3

Questão 1-e) A + A2, nos indica que podemos ir de i para j em no máximo dois passos; A3 nos mostra que podemos ir de i para j em 3 passos; e por fim, A + A2 + A3 nos mostra que podemos ir de j até i em 3 passos, pois por exemplo: A1 + A2....+Ak. k, sempre será o número de passos

Questão 1-f) Significaria que tanto i pode transmitir para j quanto j pode transmitir para i. Ou seja, podemos ir de j até i em A2 em 2 saltos, ou de i para j em A2 igualmente.O mesmo vale para A3

Questão2-a) Para nós, humanos, o método de Gauss-jordan, para computadores, o método de Gaus

Questão2-b) O método de Gaus, levando 10ms

Questão2-c)Não, todos conseguiram dar o resultado

In [32]:
%%time
#Time pega o tempo pra rodar a célula
import numpy as np

def gauss_jordan_completo(matriz_aumentada):
    """Método de Gauss-Jordan com todos os passos detalhados"""
    matriz = matriz_aumentada.astype(float)
    n = len(matriz)

    print("MATRIZ AUMENTADA INICIAL:")
    print(matriz)
    print()

    # Fase de eliminação
    for i in range(n):
        # Pivoteamento parcial
        max_row = i
        for k in range(i + 1, n):
            if abs(matriz[k, i]) > abs(matriz[max_row, i]):
                max_row = k

        if max_row != i:
            matriz[[i, max_row]] = matriz[[max_row, i]]
            print(f"Troca linha {i+1} com linha {max_row+1}:")
            print(matriz)
            print()

        # Normalizar o pivô
        pivot = matriz[i, i]
        if pivot == 0:
            raise ValueError("Sistema singular")

        matriz[i] = matriz[i] / pivot
        print(f"Linha {i+1} ÷ {pivot}:")
        print(matriz)
        print()

        # Eliminar outras linhas
        for k in range(n):
            if k != i:
                factor = matriz[k, i]
                matriz[k] = matriz[k] - factor * matriz[i]
                print(f"Linha {k+1} - {factor} × Linha {i+1}:")
                print(matriz)
                print()

    return matriz[:, -1]

# Matriz aumentada do sistema
matriz_aumentada = np.array([
    [1, 1, 1, 1, 0],
    [1, 1, 1, -1, 4],
    [1, 1, -1, 1, -4],
    [1, -1, 1, 1, 2]
])

print("="*60)
print("MÉTODO DE GAUSS-JORDAN")
print("="*60)

solucao_gj = gauss_jordan_completo(matriz_aumentada)
print("SOLUÇÃO PELO MÉTODO DE GAUSS-JORDAN:")
for i, x in enumerate(solucao_gj, 1):
    print(f"x{i} = {x:.2f}")

MÉTODO DE GAUSS-JORDAN
MATRIZ AUMENTADA INICIAL:
[[ 1.  1.  1.  1.  0.]
 [ 1.  1.  1. -1.  4.]
 [ 1.  1. -1.  1. -4.]
 [ 1. -1.  1.  1.  2.]]

Linha 1 ÷ 1.0:
[[ 1.  1.  1.  1.  0.]
 [ 1.  1.  1. -1.  4.]
 [ 1.  1. -1.  1. -4.]
 [ 1. -1.  1.  1.  2.]]

Linha 2 - 1.0 × Linha 1:
[[ 1.  1.  1.  1.  0.]
 [ 0.  0.  0. -2.  4.]
 [ 1.  1. -1.  1. -4.]
 [ 1. -1.  1.  1.  2.]]

Linha 3 - 1.0 × Linha 1:
[[ 1.  1.  1.  1.  0.]
 [ 0.  0.  0. -2.  4.]
 [ 0.  0. -2.  0. -4.]
 [ 1. -1.  1.  1.  2.]]

Linha 4 - 1.0 × Linha 1:
[[ 1.  1.  1.  1.  0.]
 [ 0.  0.  0. -2.  4.]
 [ 0.  0. -2.  0. -4.]
 [ 0. -2.  0.  0.  2.]]

Troca linha 2 com linha 4:
[[ 1.  1.  1.  1.  0.]
 [ 0. -2.  0.  0.  2.]
 [ 0.  0. -2.  0. -4.]
 [ 0.  0.  0. -2.  4.]]

Linha 2 ÷ -2.0:
[[ 1.  1.  1.  1.  0.]
 [-0.  1. -0. -0. -1.]
 [ 0.  0. -2.  0. -4.]
 [ 0.  0.  0. -2.  4.]]

Linha 1 - 1.0 × Linha 2:
[[ 1.  0.  1.  1.  1.]
 [-0.  1. -0. -0. -1.]
 [ 0.  0. -2.  0. -4.]
 [ 0.  0.  0. -2.  4.]]

Linha 3 - 0.0 × Linha 2:
[[ 1.  0.  1.  1

In [33]:

#Time pega o tempo pra rodar a célula
def eliminacao_gaussiana(matriz_aumentada):
    """Método de Gauss com substituição retroativa"""
    matriz = matriz_aumentada.astype(float)
    n = len(matriz)

    print("\n" + "="*60)
    print("MÉTODO DE GAUSS (ELIMINAÇÃO GAUSSIANA)")
    print("="*60)

    print("Matriz aumentada inicial:")
    print(matriz)
    print()

    # Fase de eliminação para frente
    for i in range(n):
        # Pivoteamento parcial
        max_row = i
        for k in range(i + 1, n):
            if abs(matriz[k, i]) > abs(matriz[max_row, i]):
                max_row = k

        if max_row != i:
            matriz[[i, max_row]] = matriz[[max_row, i]]
            print(f"Troca linha {i+1} com linha {max_row+1}")

        # Eliminar abaixo do pivô
        for k in range(i + 1, n):
            factor = matriz[k, i] / matriz[i, i]
            matriz[k] = matriz[k] - factor * matriz[i]
            print(f"Linha {k+1} - {factor:.2f} × Linha {i+1}")

        print(f"Após eliminação da coluna {i+1}:")
        print(np.round(matriz, 2))
        print()

    # Fase de substituição retroativa
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = matriz[i, -1]
        for j in range(i+1, n):
            x[i] -= matriz[i, j] * x[j]
        x[i] /= matriz[i, i]

    return x

solucao_gauss = eliminacao_gaussiana(matriz_aumentada)
print("SOLUÇÃO PELO MÉTODO DE GAUSS:")
for i, x in enumerate(solucao_gauss, 1):
    print(f"x{i} = {x:.2f}")



MÉTODO DE GAUSS (ELIMINAÇÃO GAUSSIANA)
Matriz aumentada inicial:
[[ 1.  1.  1.  1.  0.]
 [ 1.  1.  1. -1.  4.]
 [ 1.  1. -1.  1. -4.]
 [ 1. -1.  1.  1.  2.]]

Linha 2 - 1.00 × Linha 1
Linha 3 - 1.00 × Linha 1
Linha 4 - 1.00 × Linha 1
Após eliminação da coluna 1:
[[ 1.  1.  1.  1.  0.]
 [ 0.  0.  0. -2.  4.]
 [ 0.  0. -2.  0. -4.]
 [ 0. -2.  0.  0.  2.]]

Troca linha 2 com linha 4
Linha 3 - -0.00 × Linha 2
Linha 4 - -0.00 × Linha 2
Após eliminação da coluna 2:
[[ 1.  1.  1.  1.  0.]
 [ 0. -2.  0.  0.  2.]
 [ 0.  0. -2.  0. -4.]
 [ 0.  0.  0. -2.  4.]]

Linha 4 - -0.00 × Linha 3
Após eliminação da coluna 3:
[[ 1.  1.  1.  1.  0.]
 [ 0. -2.  0.  0.  2.]
 [ 0.  0. -2.  0. -4.]
 [ 0.  0.  0. -2.  4.]]

Após eliminação da coluna 4:
[[ 1.  1.  1.  1.  0.]
 [ 0. -2.  0.  0.  2.]
 [ 0.  0. -2.  0. -4.]
 [ 0.  0.  0. -2.  4.]]

SOLUÇÃO PELO MÉTODO DE GAUSS:
x1 = 1.00
x2 = -1.00
x3 = 2.00
x4 = -2.00


In [34]:

def metodo_cramer(A, b):
    """Método de Cramer para resolver sistemas lineares"""
    print("\n" + "="*60)
    print("MÉTODO DE CRAMER")
    print("="*60)

    det_A = np.linalg.det(A)
    print(f"det(A) = {det_A}")

    if abs(det_A) < 1e-10:
        raise ValueError("Sistema não tem solução única")

    solucao = []
    n = len(A)

    for i in range(n):
        # Criar matriz A_i substituindo coluna i por b
        A_i = A.copy()
        A_i[:, i] = b

        det_A_i = np.linalg.det(A_i)
        x_i = det_A_i / det_A
        solucao.append(x_i)

        print(f"\nMatriz A_{i+1}:")
        print(A_i)
        print(f"det(A_{i+1}) = {det_A_i}")
        print(f"x{i+1} = {det_A_i}/{det_A} = {x_i:.2f}")

    return solucao

# Separar matriz de coeficientes e vetor de termos independentes
A = matriz_aumentada[:, :-1]
b = matriz_aumentada[:, -1]

print("Matriz de coeficientes A:")
print(A)
print("\nVetor b:")
print(b)

solucao_cramer = metodo_cramer(A, b)
print("\nSOLUÇÃO PELO MÉTODO DE CRAMER:")
for i, x in enumerate(solucao_cramer, 1):
    print(f"x{i} = {x:.2f}")

Matriz de coeficientes A:
[[ 1  1  1  1]
 [ 1  1  1 -1]
 [ 1  1 -1  1]
 [ 1 -1  1  1]]

Vetor b:
[ 0  4 -4  2]

MÉTODO DE CRAMER
det(A) = 7.999999999999998

Matriz A_1:
[[ 0  1  1  1]
 [ 4  1  1 -1]
 [-4  1 -1  1]
 [ 2 -1  1  1]]
det(A_1) = 7.999999999999998
x1 = 7.999999999999998/7.999999999999998 = 1.00

Matriz A_2:
[[ 1  0  1  1]
 [ 1  4  1 -1]
 [ 1 -4 -1  1]
 [ 1  2  1  1]]
det(A_2) = -7.999999999999998
x2 = -7.999999999999998/7.999999999999998 = -1.00

Matriz A_3:
[[ 1  1  0  1]
 [ 1  1  4 -1]
 [ 1  1 -4  1]
 [ 1 -1  2  1]]
det(A_3) = 15.999999999999998
x3 = 15.999999999999998/7.999999999999998 = 2.00

Matriz A_4:
[[ 1  1  1  0]
 [ 1  1  1  4]
 [ 1  1 -1 -4]
 [ 1 -1  1  2]]
det(A_4) = -15.999999999999998
x4 = -15.999999999999998/7.999999999999998 = -2.00

SOLUÇÃO PELO MÉTODO DE CRAMER:
x1 = 1.00
x2 = -1.00
x3 = 2.00
x4 = -2.00
